name: A workflow for updating discovery artifacts
# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Update Discovery Artifacts PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ./branch

      - name: Create branch
        run: |
          git checkout -b update-discovery-artifacts
        working-directory: ./branch

      - name: Clone discovery artifacts from discovery-artifact manager
        uses: actions/checkout@v2
        with:
          repository: googleapis/discovery-artifact-manager
          path: ./discovery-artifact-manager

      - name: Copy discovery artifacts
        run: |
          cp ./discovery-artifact-manager/discoveries/* ./branch/googleapiclient/discovery_cache/documents/
          ls ./branch/googleapiclient/discovery_cache/documents
