name: A workflow for updating discovery artifacts
# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Update Discovery Artifacts PR
    runs-on: ubuntu-latest
    steps:
      # - name: Check out working directory for changes
      #   uses: actions/checkout@v2
      #   with:
      #     ref: refs/heads/main
      #     path: ./branch
      #     fetch-depth: '0'

      # - name: Check out branch with scripts
      #   uses: actions/checkout@v2
      #   with:
      #     ref: refs/heads/first-action
      #     path: ./branch_with_scripts
      #     fetch-depth: '0'

      # - name: Check out main
      #   uses: actions/checkout@v2
      #   with:
      #     ref: refs/heads/main
      #     path: ./main

      # - name: Create branch
      #   run: |
      #     git checkout -b update-discovery-artifacts
      #   working-directory: ./branch

      # - name: Clone discovery artifacts from discovery-artifact manager
      #   uses: actions/checkout@v2
      #   with:
      #     repository: googleapis/discovery-artifact-manager
      #     path: ./discovery-artifact-manager

      # - name: Copy scripts
      #   run: |
      #     cp ../branch_with_scripts/changesummary.py changesummary.py
      #     cp ../branch_with_scripts/create_commits.sh create_commits.sh
      #   working-directory: ./branch

      # - name: Copy discovery artifacts
      #   run: |
      #     cp ../discovery-artifact-manager/discoveries/*.json googleapiclient/discovery_cache/documents/
      #   working-directory: ./branch

      # - name: Get changed discovery artifacts
      #   run: git diff origin/main --name-only -- '*.json' |
      #         sed 's/.*\///' > changed_files
      #   working-directory: ./branch

      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.9

      # - name: Install pandas
      #   run: pip3 install pandas

      # - name: Install google-api-python-client
      #   run: pip3 install -e .
      #   working-directory: ./branch

      # - name: Patch to run the next step
      #   run: sed -i -e 's/if credentials is None/if False/g' googleapiclient/discovery.py
      #   working-directory: ./branch

      # - name: Update the docs
      #   run: python3 describe.py
      #   working-directory: ./branch

      # - name: Run Change Summary
      #   run: python3 changesummary.py
      #   working-directory: ./branch

      # - name: Commit changes
      #   run: ./create_commits.sh
      #   working-directory: ./branch

      # - name: Push changes
      #   run: git push -f --set-upstream origin update-discovery-artifacts
      #   working-directory: ./branch

      # - name: Prepare summary for PR Body
      #   id: pr_body
      #   shell: bash
      #   run: |
      #     output=$(cat temp/allapis.summary)
      #     output="${output//'%'/'%25'}"
      #     output=g
      #     output="${output//$'\r'/'%0D'}"
      #     echo "::set-output name=change_summary::$output"
      #   working-directory: ./branch

      - name: Create PR
        uses: actions/github-script@v2.0.0
        with:
          script: |

              const pull_requests = await github.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  head: 'update-discovery-artifacts',
                  base: 'main',
                  state: 'open'
                });
              console.log(pull_requests.data.length)

      # let newBody = ${{ steps.pr_body.outputs.change_summary }}
      # if (pull_requests.data.length > 0) {
      #   prNumber = pull_requests.data[0].number
      #   await github.pulls.update({
      #     owner: context.repo.owner,
      #     repo: context.repo.repo,
      #     pull_number: prNumber,
      #     title: "test1",
      #     body: "body1"
      #   });
      #   console.log('Updated PR')
      # }
      # else {
      #     const createPrResult = await github.pulls.create({
      #       owner: context.repo.owner,
      #       repo: context.repo.repo,
      #       base: "main",
      #       head: "update-discovery-artifacts",
      #       title: "test2",
      #       body: "body2"
      #   });
      # prNumber = createPrResult.data.number
      # console.log('Created PR')

      # github.issues.addLabels({
      #   owner: context.repo.owner,
      #   repo: context.repo.repo,
      #   issue_number: prNumber,
      #   labels: [auto-merge']
      # });
      # - name: Copy output for PR Body
      #   run: |
      #     output=$(cat allapis.summary)
      #     output="${output//'%'/'%25'}"
      #     output="${output//$'\n'/'%0A'}"
      #     output="${output//$'\r'/'%0D'}"
      #     echo "::set-output name=change_summary::$output"

        # - name: Update PR Body
        # uses: actions/github-script@v2.0.0
        # with:
        #   script: |
        #     let newBody = ${{ steps.get_change_summary.outputs.change_summary }}
        #     github.issues.update({
        #       issue_number: context.issue.number,
        #       owner: context.repo.owner,
        #       repo: context.repo.repo,
        #       body: newBody
        #     })
