name: A workflow for updating discovery artifacts
# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Update Discovery Artifacts PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v2
        with:
          path: ./main

      - name: Check out working directory for changes
        uses: actions/checkout@v2
        with:
          path: ./branch
          fetch-depth: '0'

      - name: Create branch
        run: |
          git checkout -b update-discovery-artifacts
        working-directory: ./branch

      - name: Clone discovery artifacts from discovery-artifact manager
        uses: actions/checkout@v2
        with:
          repository: googleapis/discovery-artifact-manager
          path: ./discovery-artifact-manager

      - name: Copy discovery artifacts
        run: |
          cp *.json ../../branch/googleapiclient/discovery_cache/documents/
        working-directory: ./discovery-artifact-manager/discoveries

      - name: Get changed discovery artifacts
        run: |
            git diff origin/main --name-only -- '*.json' | sed 's/.*\///' > ../changed_files
            cat ../changed_files
        working-directory: ./branch

