name: A workflow for updating discovery artifacts
# Controls when the action will run.
on:
  # Triggers the workflow on push to main
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Update Discovery Artifacts PR
    runs-on: ubuntu-latest
    steps:
      - name: Clone discovery artifacts
        uses: actions/checkout@v2
        with:
          name: googleapis/discovery-artifact-manager
          path: ./discovery-artifact-manager
          fetch-depth: '0'
      - name: Check code
        run: |
          ls
